// GENERATED CODE - Hive TypeAdapter for Streak model
// This file should normally be auto-generated by running: flutter packages pub run build_runner build

part of 'streak.dart';

// ignore_for_file: type=lint

class StreakAdapter extends TypeAdapter<Streak> {
  @override
  final int typeId = 0;

  @override
  Streak read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return Streak(
      id: fields[0] as String,
      name: fields[1] as String,
      emoji: fields[2] as String,
      description: fields[3] as String,
      steps: (fields[4] as List).cast<String>(),
      currentStreak: fields[5] as int,
      lastCompletedDate: fields[6] as DateTime?,
      createdAt: fields[7] as DateTime,
      bestStreak: fields[8] as int,
      totalCompletions: fields[9] as int,
    );
  }

  @override
  void write(BinaryWriter writer, Streak obj) {
    writer
      ..writeByte(10)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.name)
      ..writeByte(2)
      ..write(obj.emoji)
      ..writeByte(3)
      ..write(obj.description)
      ..writeByte(4)
      ..write(obj.steps)
      ..writeByte(5)
      ..write(obj.currentStreak)
      ..writeByte(6)
      ..write(obj.lastCompletedDate)
      ..writeByte(7)
      ..write(obj.createdAt)
      ..writeByte(8)
      ..write(obj.bestStreak)
      ..writeByte(9)
      ..write(obj.totalCompletions);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreakAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

